### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by robinpaulson**
Hi,
I have asked for the upstream code of this repo to be included in the F-Droid repository.

If you don't know what F-droid is, take a look here:
f-droid.org/

I see that your fork is more developed and more recently maintained than theirs, and wonder what you'd think about us using your repo instead?

There are a number of requirements for a new app to be accepted, including the presence of a README file.

See here if you are interested in the progress of the request:
https://gitlab.com/fdroid/rfp/-/issues/1313

Please accept the PR so we can add this app to the repo.

I would also appreciate you turning on issues, so we can discuss anything else we may need.

If you don't want the burden of dealing with Issues and PRs as a result of this, I understand entirely. In that case, I may fork your project and use that as the repo which F-Droid pulls from, dealing with the Issues myself (but pushing back to upstream of course). I'll leave it two weeks, if there's no response then I'll go that route.

If none of this makes sense or is a bit out of the blue, please ask and I'll explain some more.

Many thanks,

robin

### CODE REVIEW

**Comment by robinpaulson** [comment]
I also included a few other commits that LineageOS had that you don't. This was a mistake, but they're interesting and useful to have anyway I think.

Thanks for your time.

Robin

**Comment by BAProductions** [comment]
👍.

**Comment by robinpaulson** [comment]
Excellent, thanks!

Could you turn on Issues? It's in the "settings" tab, which is a few tabs to the right of "Pull requests".

**Comment by BAProductions** [comment]
> Excellent, thanks!
> 
> Could you turn on Issues? It's in the "settings" tab, which is a few tabs to the right of "Pull requests".

Done

**Pull request merged**
